name: foodie_seller
description: Foodie Seller - The next genration food seller with realtime updates and amazing UI.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  firebase_core: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf

